# Generated by Django 4.2.27 on 2025-12-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('ORG_ADMIN', 'Organization Admin'), ('AGRONOMIST', 'Agronomist'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=20),
        ),
    ]
