# Generated by Django 4.2.27 on 2026-08-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_membership_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('ORG_ADMIN', 'Organization Admin'), ('AGRONOMIST', 'Agronomist'), ('VIEWER', 'Viewer')], default='VIEWER', max_length=20),
        ),
    ]
