# Generated by Django 4.2.27 on 2026-01-20 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('organizations', '0002_alter_membership_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(help_text='General location or address', max_length=255)),
                ('total_area_hectares', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='organizations.organization')),
                ('owner', models.ForeignKey(blank=True, help_text='The user who owns/manages this specific farm', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_farms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('crop_type', models.CharField(choices=[('MAIZE', 'Maize'), ('BEANS', 'Beans'), ('WHEAT', 'Wheat'), ('COFFEE', 'Coffee'), ('TEA', 'Tea'), ('OTHER', 'Other')], default='MAIZE', max_length=20)),
                ('area_hectares', models.DecimalField(decimal_places=2, help_text='Size of this specific field', max_digits=10)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='farms.farm')),
            ],
        ),
    ]
