# Generated by Django 4.2.27 on 2026-02-22 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(choices=[('MAIZE', 'Maize'), ('BEANS', 'Beans'), ('WHEAT', 'Wheat'), ('COFFEE', 'Coffee'), ('TEA', 'Tea'), ('OTHER', 'Other')], default='MAIZE', max_length=50)),
                ('season_name', models.CharField(help_text='e.g., Long Rains 2026', max_length=100)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('GROWING', 'Growing'), ('HARVESTED', 'Harvested'), ('FAILED', 'Failed')], default='PLANNED', max_length=20)),
                ('planting_date', models.DateField(blank=True, null=True)),
                ('expected_harvest_date', models.DateField(blank=True, null=True)),
                ('actual_harvest_date', models.DateField(blank=True, null=True)),
                ('target_yield_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('actual_yield_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='farms.field')),
            ],
        ),
        migrations.CreateModel(
            name='FarmActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('SOIL_TEST', 'Soil Testing'), ('PLANTING', 'Planting'), ('FERTILIZER', 'Fertilizer Application'), ('WATER_CONSERVATION', 'Water & Soil Conservation'), ('WEEDING', 'Weeding / Herbicide'), ('HARVESTING', 'Harvesting')], max_length=50)),
                ('activity_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='farms.cropseason')),
            ],
            options={
                'verbose_name_plural': 'Farm Activities',
                'ordering': ['-activity_date'],
            },
        ),
    ]
