# Generated by Django 4.2.27 on 2025-12-21 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_alter_membership_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SoilSample',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('label', models.CharField(help_text="User-defined name for the sample location (e.g. 'Field A - North')", max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('depth_cm', models.PositiveIntegerField(default=15, help_text='The depth at which the sample was taken')),
                ('crop_type', models.CharField(blank=True, help_text='Current or planned crop', max_length=100)),
                ('ph', models.FloatField(help_text='Soil acidity/alkalinity')),
                ('nitrogen', models.FloatField(blank=True, help_text='mg/kg or ppm', null=True)),
                ('phosphorus', models.FloatField(blank=True, help_text='mg/kg or ppm', null=True)),
                ('potassium', models.FloatField(blank=True, help_text='mg/kg or ppm', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Extra data like lab IDs or sensor brand')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_samples', to='organizations.organization')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_soil_samples', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'created_at'], name='samples_soi_organiz_a95824_idx')],
            },
        ),
    ]
