# Generated by Django 4.2.27 on 2025-12-21 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('samples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soilsample',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_soil_samples', to=settings.AUTH_USER_MODEL),
        ),
    ]
