"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import dj_database_url
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")
DEBUG = os.getenv("DJANGO_DEBUG") == "1"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    "organizations",
    "accounts",
    "samples",
    'subscriptions',
    'predictions',
    'farms',
    "rest_framework",
    'drf_spectacular',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    "organizations.middleware.OrganizationMiddleware",
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

DATABASES = {
    'default': dj_database_url.config(
        default=os.environ.get('DATABASE_URL')
    )
}

#DATABASES = {
#    "default": {
#        "ENGINE": "django.db.backends.postgresql",
#        "NAME": os.getenv("POSTGRES_DB"),
#        "USER": os.getenv("POSTGRES_USER"),
#        "PASSWORD": os.getenv("POSTGRES_PASSWORD"),
#        "HOST": os.getenv("POSTGRES_HOST"),
#        "PORT": os.getenv("POSTGRES_PORT"),
#    }
#}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = "accounts.User"

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),

    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Celery Configuration
CELERY_BROKER_URL = "redis://redis:6379/0"
CELERY_RESULT_BACKEND = "redis://redis:6379/0"
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',  # <--- This allows INFO logs to show up
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Explicitly capture your app logs
        'predictions': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'organizations': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
        'subscriptions': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# Swagger Settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Agritech SaaS Intelligence & Farm Management API',
    'DESCRIPTION': """
#  Agritech SaaS Backend API Documentation

Welcome to the **Agritech SaaS Backend API**! This platform provides an enterprise-grade, multi-tenant architecture designed for agricultural cooperatives, agribusinesses, and agronomists to manage farm operations, track crop lifecycle timelines, record agronomic interventions, and run high-performance predictive soil analytics.

---

### Getting Started & Onboarding Flow

Because this platform operates on a **strict multi-tenant architecture**, every action (farms, fields, soil samples, and predictions) must belong to an **Organization** context.

Follow these 4 simple steps to get started:

1. **Register an Account:**
   - Call `POST /api/accounts/register/` with your `email` and `password`.
   - The response will return your user record along with initial JWT `access` and `refresh` tokens.
   - Alternatively, existing users can log in via `POST /api/auth/login/`.

2. **Authorize in Swagger UI:**
   - Click the **"Authorize"** button (green lock icon) at the top-right of this page.
   - In the value box, enter your access token in the format:
     `Bearer YOUR_ACCESS_TOKEN`
     *(Example: `Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6...`)*
   - Click **Authorize** -> **Close**. All requests made from this page will now include your token automatically.

3. **Provision Your Organization (Tenant Workspace):**
   - Call `POST /api/organizations/create/` with your organization name (e.g., `{"name": "Green Valley Cooperative"}`).
   - You will automatically be assigned as the **`OWNER`** of this workspace with an active **`FREE`** tier subscription.

4. **Start Managing Farms & Predicting Soil Health:**
   - Create Farms: `POST /api/agronomy/farms/`
   - Add Plots/Fields: `POST /api/agronomy/fields/`
   - Trigger Asynchronous Soil Predictions: `POST /api/predict/`

---

###  Core API Modules

- **Authentication & Accounts (`/api/accounts/` & `/api/auth/`):** User registration, token issuance, refresh cycles, and profile inspection.
- **Multi-Tenancy & Organizations (`/api/organizations/`):** Workspace provisioning, tenant scoping, and role inspection.
- **Farms, Fields & Crop Timelines (`/api/agronomy/`):** Geospatial field mapping, planting schedules, target yield tracking, and farm activities.
- **Soil Sampling & Spectra Analytics (`/api/samples/` & `/api/predict/`):** NPK soil logging and asynchronous machine learning prediction jobs powered by Celery & Redis.
- **Subscriptions & Monetization (`/api/subscriptions/`):** Stripe B2B billing integration, checkout workflows, and plan tier limits.
    """,
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
}

# Folder for uploaded files
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# --- STRIPE BILLING CONFIGURATION ---
STRIPE_PUBLIC_KEY = os.environ.get('STRIPE_PUBLIC_KEY')
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET')
STRIPE_PRO_PRICE_ID = os.environ.get('STRIPE_PRO_PRICE_ID')

# --- CORS CONFIGURATION ---
# This allows your React frontend (e.g., localhost:3000) to talk to the API
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')
CORS_ALLOWED_ORIGINS = [
    FRONTEND_URL,
]

# --- STATIC FILES (WhiteNoise) ---
# Tell Django where to gather all static files for production
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
# Tell WhiteNoise to compress the files and cache them for speed
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
