name: Prevent Supabase Inactivity

on:
  schedule:
    - cron: "0 0 * * 0,4" # Runs at midnight UTC every Sunday and Thursday
  workflow_dispatch: # Allows you to click a button to run it manually

jobs:
  ping-database:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase API
        run: |
          curl -X GET "${{ secrets.SUPABASE_URL }}/rest/v1/farms_farm?select=id&limit=1" \
          -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}"
